// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR_7x2Ynziv823vMS-lz5PAaBdD92xLD4',
    appId: '1:611650116188:web:0c25fab6aba671cef82499',
    messagingSenderId: '611650116188',
    projectId: 'borae-34b9e',
    authDomain: 'borae-34b9e.firebaseapp.com',
    storageBucket: 'borae-34b9e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAapS8I1t9qEa-90AvjNg72d8M8WqPlGGE',
    appId: '1:611650116188:android:f8fb78a17e89dd6ff82499',
    messagingSenderId: '611650116188',
    projectId: 'borae-34b9e',
    storageBucket: 'borae-34b9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_AAasASBhPFNYHb3zfj-N2VWGH5zSJ5U',
    appId: '1:611650116188:ios:cc05ae053e5dbd0cf82499',
    messagingSenderId: '611650116188',
    projectId: 'borae-34b9e',
    storageBucket: 'borae-34b9e.firebasestorage.app',
    iosBundleId: 'com.example.boraeApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_AAasASBhPFNYHb3zfj-N2VWGH5zSJ5U',
    appId: '1:611650116188:ios:cc05ae053e5dbd0cf82499',
    messagingSenderId: '611650116188',
    projectId: 'borae-34b9e',
    storageBucket: 'borae-34b9e.firebasestorage.app',
    iosBundleId: 'com.example.boraeApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR_7x2Ynziv823vMS-lz5PAaBdD92xLD4',
    appId: '1:611650116188:web:5f8a96626716589df82499',
    messagingSenderId: '611650116188',
    projectId: 'borae-34b9e',
    authDomain: 'borae-34b9e.firebaseapp.com',
    storageBucket: 'borae-34b9e.firebasestorage.app',
  );

}